language: python

script:
  - echo "no tests"

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: dougip2
  password:
    secure: "ooAbHJ+SEPqq2t9bKmzY8bZKzn4kw6PzxJKgHgb/dkv9NJrNby2XRT9M/TVz0V0cT8tpj4F4Ipyal+xVYGNqXbj3XkzVabG+KhySvVLnXisv1sCCOfxfQoyJGupdlErklF2s1JE4zN/jEKKa45uklGrRlttVENmGHH8TSzwo2HDhLT6EpvBJ3YQfuUxZxD4I9oR+DOa3RzJwr53s5D1NokXmuKMjLVvsSL9zkVtkzF2lUf6vbwqf5uesCbf0neZxjaSg46EU4fJs20voI0oeV6nOC83DBgbInYsdTOVrcY1aqHjRRfpSBrY2GqyEQSAKiPZSplSi33RdW6guqCl1tCPUCxXKr97GljpHBfHTJ6yRtzfxigFcrQzn/1UHG6318JYOlQdlmXHlED//NmfEy6Z2bSnsDKiG0ngiBN7XpXMhjhjJsXNzeBDl3grZqrlCRby3KtukCFikiOz3C3OnWp9xa4CPr04grjyvzDogAgrI6l3qbyXmBqeR2+ea9qBnGCTgNS3iy+5n8vievbyVFxxWMzuUquk5mzQ59vyg63eYSw8lL8kSARsviPT1M3AeV5PgEqIhPX/lzcG4zC86krmYY5GM+r4gVj7vq/pIEMIhePnS27MbTxWlh4I1mGjt3TRMNW4WQoFhPzjfTBB5HrkG+R4zjN5jALS0xpWNHcQ="
  on:
    branch: test
